### PR TITLE
Finished the project Website Teardown

### PR DESCRIPTION
**Pull request by markonikovic**
For this project, we used CSS-grid, flex-box and floats to position the elements on the page. We didn't actually completely clone the page, just it's the layout.
We also used different shades of gray to highlight the visually dominant content with a darker shade of gray while we use lighter shades for less dominant content. We used three different font styles from Google Fonts, different font-weights to mimic the typography of the target page. 
We used semantic HTML tags and before the pull request, we verified HTML and CSS files with W3CValidator and StyleLint.

### CODE REVIEW

**Comment by davitomix** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davitomix** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi Team. 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****
### 2 articles rows

- [ ] It contains 2 articles, each takes half of the width (content is not important).
This goes after the navbar, on the original page we can see that it has 2 rows with 2 articles each one.

Your page. ⬇️ 

Screen Shot 2020-03-05 at 10 25 47 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-05 at 10 26 54 PM

****
### 3 articles rows

- [ ] It contains 3 articles, each takes one-third of the width (content is not important).
After the point that I listed above follows the row with 3 articles that you already have.
So you only have to ADD the 2 by 2 row before this row, which is the point I listed before.

****
### Footer

- [ ] It contains centered links.
Center the links on the footer following the based page. 
You can follow the patterns listed below.

Screen Shot 2020-03-05 at 10 35 55 PM

Screen Shot 2020-03-05 at 10 36 27 PM

****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by markonikovic** [comment]
Hi David, you reviewed our code for the SmashingMagazie website project, and you mentioned using a two-column layout but it's not how it appears on my screen. Please take into consideration that people have different monitor sizes, for example, my monitor is 24 inch and the website displays like this. For the footer section, it looked like a background image to me but we can easily create the layout you desire.

https://files.slack.com/files-pri/T47CT8XPG-FUZ9FAWS1/image.png

**Comment by markonikovic** [comment]
image

**Comment by uryelah** [comment]
Hello **Marko Nikovic** & **Alvaro Paz Rosero**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Your project is a good start but you need to work on it a bit more 💪 **

---------    

**Great job at: 🥇** 
- making a good readme
- using semantic HTML
- using only shades of grey for the project

**You still need to fix the issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] Like the last TSE pointed out, please fix your footer so the text is centered and organized the same way as the original page. Check the images he linked again.

> It contains centered links.
> Center the links on the footer following the based page.
> You can follow the patterns listed below.

- [ ] The areas of the site that have only one article that takes 100% of the width of the page should use the `<article>` instead of the `<div>` tag. [Interesting reading on when to use the article tag.](https://bitsofco.de/sectioning-content-in-html5/)

- [ ] This page has a lot of visual elements, nav images, images in the articles, etc.
You need to represent their weight in the design tear-down.
Check [this project](https://rawcdn.githack.com/santiago-rodrig/design-teardown/0b0eaaf8a4a5bc584ef1a2c2715a0a66e209cd80/index.html) for reference of what yours should look like. (Ignore the changes due to screen size)

---------
###Optional Enhancements

- [ ] Change the text fonts and sizes so they match the [original site](https://www.smashingmagazine.com/).
---------
 
**Please fix the required changes 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by alvaropazz** [comment]
Hi Sarah, we corrected the footer positioning and changed the <div> element for an  <article> element. We also added some boxes to represent the top icons. However, the project description doesn't ask for images or other elements alike. 
We requested another code review, with the changes mentioned above.

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] As the last TSE says: "Like the last TSE pointed out, please fix your footer so the text is centered and organized the same way as the original page. Check the images he linked again." great job center this, but you are still missing sections here, consider follow the structure of the original page.





- [ ] As the last TSE says: "This page has a lot of visual elements, nav images, images in the articles, etc.
You need to represent their weight in the design tear-down.
Check this project for reference of what yours should look like. (Ignore the changes due to screen size)" you are missing the boxes representing the navbar, and too many sections in every main section doesn't have the little boxes representing different important sections. Consider following the original page, this project is not only to make the big boxes on gray but the little boxes on 'light gray' also have to be represented here. I saw you made some little boxes on 'light gray' but check that you are still missing more parts in your project.











_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by davitomix** [comment]
### **Status: Approved.** ✅ 
### **Congragulations!** 🎉 
****
### Hi Team. 😄 
****
Great Job 💯  @alvaropazz  @markonikovic , You correctly implemented all the changes required by previous TSE.
You can move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Pull request merged**
